language: python
python:
  - "2.7"
env:
  - DJANGO_SETTINGS_MODULE=test_settings
install:
  - "pip install coverage coveralls"
  - "pip install -e ."
script:
  - py.test -s --ds=test_settings --verbose --cov ./livechat livechat
after_success:
  - coveralls
